export default {
  results: [],
  isSearching: false,
  resultsTotalPages: null,
  resultsTotalCnt: null,
  resultsCurrentPage: null,
  genresCheckboxes: [],
  ratingRadios: [],
  searchTerm: '',
  minVoteCountValue: '',
  countriesCheckboxes: [],
  searchWasRequested: false,
  yearsCheckboxes: [],
  searchPageScrollPosition: null,
  topScrollPosition: 0,
  releaseTypesCheckboxes: [],
  sortType: 'popularity',
  sortOrder: 'desc',
  params: null,
}
