export const SEARCH_BY_FILETRS = 'SEARCH_BY_FILTERS';
export const SET_IS_SEARCHING = 'SET_IS_SEARCHING';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const SET_RESULTS_TOTAL_PAGES = 'SET_RESULTS_TOTAL_PAGES';
export const SET_RESULTS_CURRENT_PAGE = 'SET_RESULTS_CURRENT_PAGE';
export const SET_RESULTS_TOTAL_CNT = 'SET_RESULTS_TOTAL_CNT';

