export const SEARCH_BY_FILETRS = 'SEARCH_BY_FILTERS';
export const SET_IS_SEARCHING = 'SET_IS_SEARCHING';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const SET_RESULTS_TOTAL_PAGES = 'SET_RESULTS_TOTAL_PAGES';
export const SET_RESULTS_CURRENT_PAGE = 'SET_RESULTS_CURRENT_PAGE';
export const SET_RESULTS_TOTAL_CNT = 'SET_RESULTS_TOTAL_CNT';
export const SET_GENRES_CHECKBOXES = 'SET_GENRES_CHECKBOXES';
export const SET_RATING_RADIOS = 'SET_RATING_RADIOS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_MIN_VOTE_COUNT_VALUE = 'SET_MIN_VOTE_COUNT_VALUE';
export const SET_COUNTRIES_CHECKBOXES = 'SET_COUNTRIES_CHECKBOXES';
export const SET_SEARCH_WAS_REQUESTED = 'SET_SEARCH_WAS_REQUESTED';
export const SET_YEARS_CHECKBOXES = 'SET_YEARS_CHECKBOXES';
export const CLEAR_ALL_SEARCH_STORE = 'CLEAR_ALL_SEARCH_STORE';

