export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_NEW_MOVIES = 'FETCH_NEW_MOVIES';
export const FETCH_MOVIES_GENRES = 'FETCH_MOVIES_GENRES';
export const FETCH_CURRENT_MOVIE = 'FETCH_CURRENT_MOVIE';
export const FETCH_CURRENT_MOVIE_SIMILAR = 'FETCH_CURRENT_MOVIE_SIMILAR';
export const FETCH_CURRENT_MOVIE_RECOMMENDATIONS = 'FETCH_CURRENT_MOVIE_RECOMMENDATIONS';
export const CLEAR_CURRENT_MOVIE = 'CLEAR_CURRENT_MOVIE';
