export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_NEW_MOVIES = 'FETCH_NEW_MOVIES';
export const FETCH_MOVIES_GENRES = 'FETCH_MOVIES_GENRES';
export const FETCH_CURRENT_MOVIE = 'FETCH_CURRENT_MOVIE';
