export const FETCH_POPULAR_TV_SHOWS = 'FETCH_POPULAR_TV_SHOWS';
export const FETCH_NEW_TV_SHOWS = 'FETCH_NEW_TV_SHOWS';
export const FETCH_TV_SHOWS_GENRES = 'FETCH_TV_SHOWS_GENRES';
export const FETCH_CURRENT_TV_SHOW = 'FETCH_CURRENT_TV_SHOW';
export const CLEAR_CURRENT_TV_SHOW = 'CLEAR_CURRENT_TV_SHOW';
